services:
  web:
    environment:
      CADDY_PHP_SERVER_EXTRA_DIRECTIVES: |
        hot_reload
        worker {
          file /app/public/index.php
          watch /app/src/**/*.php
          watch /app/public/**/*.php
          watch /app/templates/**/*.php
        }
