services:
  php:
    build:
      context: .
      target: dev
    ports:
      - "${APP_PORT:-80}:${APP_PORT:-80}"
    environment:
      SERVER_NAME: ":${APP_PORT:-80}"
      CADDY_GLOBAL_OPTIONS: >-
        log {
          output file /app/logs/frankenphp/caddy.log
          format json {
            time_format wall
          }
        }
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config

  composer:
    profiles:
      - tools
    build:
      context: .
      target: composer
    volumes:
      - ./:/app

volumes:
  caddy_data:
  caddy_config: