<?php

$value = $_ENV['APP_ENV'];
$name = $_SERVER['SERVER_NAME'];

?>
-----
<?php

// TODO: [ForbidMagicStringArrayKeyRector] Constants name things. Define a public const with value 'APP_ENV' on the appropriate class.
$value = $_ENV['APP_ENV'];
// TODO: [ForbidMagicStringArrayKeyRector] Constants name things. Define a public const with value 'SERVER_NAME' on the appropriate class.
$name = $_SERVER['SERVER_NAME'];

?>
