<?php

$options = [
    'cache' => '/tmp',
    'debug' => true,
];

?>
-----
<?php

$options = [
    // TODO: [ForbidMagicStringArrayKeyRector] Constants name things. Define a public const with value 'cache' on the appropriate class.
    'cache' => '/tmp',
    // TODO: [ForbidMagicStringArrayKeyRector] Constants name things. Define a public const with value 'debug' on the appropriate class.
    'debug' => true,
];

?>
