checks:
  check:manifest:
    command: "php scripts/check-manifest.php"
    fix: "./run sync:manifest"
  check:composer:
    command: "composer validate"
  check:style:
    command: "vendor/bin/php-cs-fixer fix --dry-run --diff"
    fix: "./run fix:style"
  check:rector:
    command: "vendor/bin/rector process --dry-run"
    fix: "./run fix:rector"
  check:types:
    command: "vendor/bin/phpstan analyse"
  check:migrations:
    command: "php scripts/check-migrations.php"
  check:requirements:
    command: "php scripts/check-requirements.php"
  check:blade-routes:
    command: "php scripts/check-blade-routes.php"
  check:blade-components:
    command: "php scripts/check-blade-components.php"
  check:blade-templates:
    command: "php scripts/check-blade-templates.php"
  check:blade-push:
    command: "php scripts/check-blade-push.php"
  check:preload:
    command: "php scripts/check-preload.php"
    fix: "./run sync:preload"
  check:graph:
    command: "php scripts/check-graph.php"
  check:todos:
    command: "php scripts/check-todos.php"
  check:columns:
    command: "php scripts/check-columns.php"
  check:coverage:
    command: "php scripts/check-coverage.php"
  check:side-effect-coverage:
    command: "php scripts/check-side-effect-coverage.php"
  test:
    command: "vendor/bin/paratest"
