source_dirs:
  - /app/src
  - /app/vendor
route_class: ZeroToProd\Thryds\Routes\Route
status_class: ZeroToProd\Thryds\OpcacheStatus
dev_path_enum: ZeroToProd\Thryds\DevPath
status_endpoint: /_opcache/status
scripts_endpoint: /_opcache/scripts
preload_marker: $PRELOAD$
preload_file: /app/preload.php
