namespaces:
  viewmodels: ZeroToProd\Thryds\ViewModels
  tests_integration: ZeroToProd\Thryds\Tests\Integration
  controllers: ZeroToProd\Thryds\Controllers
  tables: ZeroToProd\Thryds\Tables
  routes: ZeroToProd\Thryds\Routes
  blade: ZeroToProd\Thryds\Blade
  enums: ZeroToProd\Thryds\UI
  schema: ZeroToProd\Framework\Schema

directories:
  templates: templates
  components: templates/components
  viewmodels: src/ViewModels
  tests_integration: tests/Integration
  controllers: src/Controllers
  tables: src/Tables
  enums: src/UI

attributes:
  viewmodel: ZeroToProd\Framework\Attributes\ViewModel
  data_model: ZeroToProd\Framework\Attributes\DataModel
  handles_route: ZeroToProd\Framework\Attributes\HandlesRoute
  covers_route: ZeroToProd\Framework\Attributes\CoversRoute
  persists: ZeroToProd\Framework\Attributes\Persists
  redirects_to: ZeroToProd\Framework\Attributes\RedirectsTo
  renders_view: ZeroToProd\Framework\Attributes\RendersView
  closed_set: ZeroToProd\Framework\Attributes\ClosedSet
  schema_sync: ZeroToProd\Framework\Attributes\SchemaSync
  table: ZeroToProd\Framework\Attributes\Table
  has_table_name: ZeroToProd\Framework\Attributes\HasTableName
  column: ZeroToProd\Framework\Attributes\Column
  primary_key: ZeroToProd\Framework\Attributes\PrimaryKey
