directory: src/Tables
namespace: ZeroToProd\Thryds\Tables
table_name_enum: TableName
data_type_enum: ZeroToProd\Thryds\Schema\DataType
data_type_map:
  bigint: BIGINT
  binary: BINARY
  blob: BLOB
  char: CHAR
  date: DATE
  datetime: DATETIME
  decimal: DECIMAL
  double: DOUBLE
  enum: ENUM
  float: FLOAT
  int: INT
  json: JSON
  longblob: LONGBLOB
  longtext: LONGTEXT
  mediumblob: MEDIUMBLOB
  mediumtext: MEDIUMTEXT
  set: SET
  smallint: SMALLINT
  text: TEXT
  time: TIME
  timestamp: TIMESTAMP
  tinyint: TINYINT
  varbinary: VARBINARY
  varchar: VARCHAR
  year: YEAR
imports:
  - ZeroToProd\Thryds\Attributes\ClosedSet
  - ZeroToProd\Thryds\Attributes\Column
  - ZeroToProd\Thryds\Attributes\DataModel
  - ZeroToProd\Thryds\Attributes\HasTableName
  - ZeroToProd\Thryds\Attributes\PrimaryKey
  - ZeroToProd\Thryds\Attributes\SchemaSync
  - ZeroToProd\Thryds\Attributes\Table
  - ZeroToProd\Thryds\Schema\Charset
  - ZeroToProd\Thryds\Schema\Collation
  - ZeroToProd\Thryds\Schema\DataType
  - ZeroToProd\Thryds\Schema\Engine
  - ZeroToProd\Thryds\Schema\SchemaSource
  - ZeroToProd\Thryds\UI\Domain
